#define PROG_BOT //COMMENT THIS OUT IF NOT TESTING ON PROGRAMMING BOT

//Cameras
//#define DRIVE_TEAM_CAM_1 //COMMENT THIS OUT IF CAMERA IS NOT ON BOT
//#define DRIVE_TEAM_CAM_2 //COMMENT THIS OUT IF CAMERA IS NOT ON BOT

//Chassis
#define LEFT_JOYSTICK_CHANNEL 0
#define RIGHT_JOYSTICK_CHANNEL 1
#define COLOR_SENSOR_PORT 0x52

#ifdef PROG_BOT
//Chassis
#define FRONT_LEFT_MOTOR_CHANNEL 1
#define REAR_LEFT_MOTOR_CHANNEL 2
#define FRONT_RIGHT_MOTOR_CHANNEL 4
#define REAR_RIGHT_MOTOR_CHANNEL 3
#endif

// Vision
#define VISION_DISTANCE "Distance to Tape"
#define VISION_OFFSET "Offset"
#define NO_DATA_DEFAULT -1000