sudo: true
dist: trusty
language: java

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - g++-multilib
      - lib32stdc++6
      - python3.5-dev

before_install:
  - sudo sh -c 'echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main" > /etc/apt/sources.list.d/llvm.list'
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo apt-get update -q || true
  - sudo apt-get install clang-format-5.0 -y

install:
  - wget https://bootstrap.pypa.io/get-pip.py
  - sudo python3.5 get-pip.py
  - python3.5 -m pip install --user wpiformat
  - ./gradlew build -PbuildAll

script:
  - python3.5 -m wpiformat -y 2018 -clang 5.0
  - git --no-pager diff --exit-code HEAD  # Ensure formatter made no changes
  - ./gradlew build -PbuildAll

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
