/* DEFINES FOR AUTO SELECTOR */
// auto modes
#define STAY_STILL 0
#define FORWARD_STILL 1
#define BACKWARD_STILL 2
#define CENTER_SHOOT 3
#define CENTER_FORWARD_SHOOT 4
#define CENTER_BACKWARD_SHOOT 5
#define CENTER_SHOOT_RONDEZVOUS 6
#define CENTER_SHOOT_TRENCH 7
#define CENTER_FORWARD_RONDEZVOUS 8
#define LEFT_FORWARD_RONDEZVOUS 9
#define RIGHT_FORWARD_RONDEZVOUS 10
#define LC_FORWARD_RONDEZVOUS 11
#define RC_FORWARD_RONDEZVOUS 12
#define CENTER_BACKWARD_RONDEZVOUS 13
#define LEFT_BACKWARD_RONDEZVOUS 14
#define RIGHT_BACKWARD_RONDEZVOUS 15
#define LC_BACKWARD_RONDEZVOUS 16
#define RC_BACKWARD_RONDEZVOUS 17
#define CENTER_FORWARD_TRENCH 18
#define LEFT_FORWARD_TRENCH 19
#define RIGHT_FORWARD_TRENCH 20
#define RC_FORWARD_TRENCH 21
#define LC_FORWARD_TRENCH 22
#define CENTER_BACKWARD_TRENCH 23
#define RIGHT_BACKWARD_TRENCH 24
#define LEFT_BACKWARD_TRENCH 25
#define LC_BACKWARD_TRENCH 26
#define RC_BACKWARD_TRENCH 27
#define CENTER_BACKWARD_SHOOT_RONDEZVOUS 28
#define RIGHT_BACKWARD_SHOOT_RONDEZVOUS 29
#define RC_BACKWARD_SHOOT_RONDEZVOUS 30
#define CENTER_BACKWARD_SHOOT_TRENCH 31
#define RIGHT_BACKWARD_SHOOT_TRENCH 32
#define RC_BACKWARD_SHOOT_TRENCH 33
#define DONE 34

// delay times
#define ZERO_SEC 0
#define ONE_SEC 1
#define TWO_SEC 2
#define THREE_SEC 3
#define FOUR_SEC 4
#define FIVE_SEC 5

// starting places
#define START_LEFT_WALL 1
#define START_RIGHT_WALL 2
#define START_CENTER_FIELD 3
#define START_RIGHT_OF_CENTER_FIELD 4 // centered with target
#define START_LEFT_OF_CENTER_FIELD 5

// step 1
#define CROSS_INITITATION_LINE_FORWARD 1
#define CROSS_INITIATION_LINE_BACKWARD 2
#define SHOOT_PRELOADED_BALLS_FIRST 3

// step 2
#define SHOOT_PRELOADED_BALLS 1
#define DRIVE_TO_RONDEVOUS_POINT 2
#define DRIVE_TO_TRENCH 3

// step 3
#define PICK_UP_BALLS_TRENCH 1
#define PICK_UP_BALLS_RONDEVOUS_POINT 2
#define DRIVE_TO_TRENCH_3 3
#define DRIVE_TO_RONDEZVOUSPT_3 4

// step 4
#define SHOOT_PICKED_UP_BALLS 1

// do nothing
#define DO_NOTHING 6