sudo: true
language: java

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - g++-multilib
      - lib32stdc++6
      - python3.5

before_install:
  - .travis-scripts/install.sh

install:
  - ./gradlew build -PbuildAll

script:
  - .travis-scripts/wpiformat.sh
  - ./gradlew build -PbuildAll

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
