version: "{branch} {build}"

image:
- Visual Studio 2015
- Visual Studio 2013

build:
  verbosity: detailed

build_script:
  - gradlew.bat assemble --info -PskipArm

test_script:
- cmd: >-
    SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0

    gradlew.bat check --info -PskipArm

    SET JAVA_HOME=C:\Program Files (x86)\Java\jdk1.8.0

    gradlew.bat check --info -PskipArm

cache:
  - C:\Users\appveyor\.gradle

matrix:
  fast_finish: true
